# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curry < Formula
  desc "curried commandline"
  homepage "https://lambdasawa/curry"
  version "0.0.3"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.3/curry_0.0.3_Darwin_arm64.tar.gz"
      sha256 "c679492b38d1d9a14cac3ab8cba1c6d6cf9c572cf2f6ff5a06bab80123f27490"

      def install
        bin.install "curry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.3/curry_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "68daabe01c1183529f1239ff6a7299aae9f6848f18f5b04a2349bdea309fce5d"

      def install
        bin.install "curry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.3/curry_0.0.3_Linux_x86_64.tar.gz"
      sha256 "27804322e2342f7483bbba4e50bd77a366e5ccbc2208d76cd1be155cce18f557"

      def install
        bin.install "curry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.3/curry_0.0.3_Linux_arm64.tar.gz"
      sha256 "42854cba5be8ad8a86a1fd4d13ce5a2209dc27f5f37cf88e963306c903991446"

      def install
        bin.install "curry"
      end
    end
  end

  depends_on "git"

  def caveats; <<~EOS
    curry <command> [args]
  EOS
  end
end
