# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curry < Formula
  desc "curried commandline"
  homepage "https://github.com/lambdasawa/curry"
  version "0.0.6"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.6/curry_0.0.6_Darwin_arm64.tar.gz"
      sha256 "1b2a66b9a3d52583d0ee5ff2de2efe3ad22fc9e6a91e661aa432f73aec51e873"

      def install
        bin.install "curry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.6/curry_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "19971f1d9bc1b485fa3764a1477713980816bc61fa00c26d4e2c80cf8b56498f"

      def install
        bin.install "curry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.6/curry_0.0.6_Linux_x86_64.tar.gz"
      sha256 "40097791d2ff355790dd0a985badf47ae0fcf8ad613006b1335eb2a236f49e3c"

      def install
        bin.install "curry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.6/curry_0.0.6_Linux_arm64.tar.gz"
      sha256 "a13872da40bb055a8e0a2478161d24771ff26d686dbcb7cecda61b342f75314d"

      def install
        bin.install "curry"
      end
    end
  end

  depends_on "git"

  def caveats; <<~EOS
    curry <command> [args]
  EOS
  end
end
