# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curry < Formula
  desc "curried commandline"
  homepage "https://github.com/lambdasawa/curry"
  version "0.0.7"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.7/curry_0.0.7_Darwin_arm64.tar.gz"
      sha256 "054c5db47fed151285d209d701cf79e9ebc7aca6df9dd9b473390c5e67439d3f"

      def install
        bin.install "curry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.7/curry_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "c8b0383312d4da8aa521e41a35c951786b16eabe2941734f8b916b28a9b8c446"

      def install
        bin.install "curry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.7/curry_0.0.7_Linux_x86_64.tar.gz"
      sha256 "69a995c4d21f881727abe1b8e161241f2b47a75f20892a538e8dc9456fa7e9d4"

      def install
        bin.install "curry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lambdasawa/curry/releases/download/v0.0.7/curry_0.0.7_Linux_arm64.tar.gz"
      sha256 "062e570cd30c4c8157c62b7e0466629fd7c5233fc07ab04744ba44cefc80d2de"

      def install
        bin.install "curry"
      end
    end
  end

  depends_on "git"

  def caveats; <<~EOS
    curry <command> [args]
  EOS
  end
end
